config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root "main#index"
  end
  root "introduce#index"
  devise_for :users, skip: %i(sessions registrations), controllers: {passwords: "devises/passwords"}
  as :user do
    get "/login", to: "devises/sessions#new", as: :new_user_session
    post "/login", to: "devises/sessions#create", as: :user_session
    delete "/logout", to: "devises/sessions#destroy", as: :destroy_user_session
    get "/users/edit", to: "devise/registrations#edit", as: :edit_user_registration
    put "/users", to: "devise/registrations#update", as: :user_registration
    get "profiles/:id", to: "users#show", as: :profiles
    patch  "user/avatar/:id", to: "users#change_avatar", as: :change_avatar
  end
  namespace :admin do
    as :user do
      patch "user/status/:id", to: "users#change_status_user", as: :change_status_user
      get "users/export/:type", to: "users#export", as: :user_export
      post "users/import", to: "users#import", as: :user_import
    end
    resources :users, except: %i(show destroy)
    resources :courses
    patch "course/status/:id", to: "courses#change_status", as: :change_status_course
    get "courses/export/:type", to: "courses#export", as: :course_export
    get "courses/export/course/:id", to: "courses#export_course", as: :course_export_course
    post "courses/import", to: "courses#import", as: :course_import
    resources :subjects
    patch "subject/status/:id", to: "subjects#change_status", as: :change_status_subject
    get "subjects/export/file", to: "subjects#export", as: :subject_export
    get "subjects/export/subject/:id", to: "subjects#export_subject", as: :subject_export_subject
    post "subjects/import", to: "subjects#import", as: :subject_import
    post "subjects/import/lessons", to: "subjects#import_lesson", as: :subject_import_lesson
    post "subjects/import/links", to: "subjects#import_link", as: :subject_import_link
    resources :lessons
    get "course/:course_id/subject/:subject_id", to: "course_subjects#show", as: :show_subject_course
    get "course/:course_id/subject/:subject_id/:status", to: "course_subjects#update", as: :update_status_cs
    resources :course_users
    resources :lessons, except: %i(new create destroy)
    get "lessons/export/exam/:id", to: "lessons#export_lesson_exam", as: :export_lesson_exam
    resources :companies, only: %i(show edit update)
  end

  namespace :trainer do
    resources :users, only: :index
    resources :courses, only: :index
  end

  namespace :trainee do
    get "exam_lessons/new/:course_user_lesson_id", to: "exam_lessons#new", as: :new_exam_lesson
    resources :exam_lessons, except: %i(new index)
    get "exam_lessons/course_user_lesson/:course_user_lesson_id", to: "exam_lessons#show_test_of_lesson", as: :show_test_of_lesson
  end
  get "myexams", to: "trainee/exams#index"
  get "course/:id", to: "admin/courses#show", as: :course
  get "course/:course_id/subject/:subject_id", to: "admin/course_subjects#show", as: :trainer_course_subject

  get "mycourses", to: "trainee/courses#index", as: :mycourses
  get "mycourse/:id", to: "admin/courses#show", as: :mycourse
  get "mycourse/:course_id/subject/:subject_id", to: "admin/course_subjects#show", as: :course_subject
  get "report/progress/:id/:status", to: "trainee/course_user_lessons#update", as: :report_progress

  get "/about", to: "test_templatee2#about", as: "about"
  get "/form/course", to: "test_templatee2#form_course", as: "form_course"
  get "/form/course/edit", to: "test_templatee2#form_course_edit", as: "form_course_edit"

  resources :registrations
  post "/registrations/accept", to: "registrations#accept_action", as: :accept_action
end

app/helpers/admin/surveys_helper.rb
module Admin::SurveysHelper
  def define_color_status_survey survey
    case survey.status
    when "ready"
      @color = "default"
      @class = "info"
      @icon = "unlock"
      @title = "CLICK để khóa bài thi"
    else
      @color = "danger"
      @class = "danger"
      @icon = "lock"
      @title = "CLICK để mở bài thi"
    end
  end
end

app/views/admin/surveys/_answer.html.erb
<li class="radio">
  <label> - <%= answer.text %></label>
</li>

app/views/admin/surveys/_answer_fields.html.erb
<div class="row nested-fields">
  <div class="col-xs-1"></div>
  <div class="col-xs-6">
    <%= f.text_field :text, class: "form-control" %>
  </div>
  <div class="checkbox col-xs-3">
    <label>
      <%= f.check_box :correct %>Đáp án đúng
    </label>

  </div>
  <div class="col-xs-2">
    <%= link_to_remove_association "Xóa", f, class: "btn btn-default btn-remove-df" %>
  </div>
</div>

app/views/admin/surveys/_form.html.erb
<div class="block-title">
  <h2>
    <strong>Bài kiểm tra</strong>
  </h2>
</div>
<%= form_for @survey, url: yield(:url_path),
  html: {class: "form-horizontal form-bordered ui-formwizard", id:"clickable-wizard"} do |f| %>
  <div id="clickable-first" class="step ui-formwizard-content">
    <div class="form-group">
      <div class="col-xs-12">
        <ul class="nav nav-pills nav-justified clickable-steps">
          <li class="active">
            <a href="javascript:void(0)" data-gotostep="clickable-first">
              <strong>1. Thông tin cần thiết</strong>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)" data-gotostep="clickable-second">
              <strong>2. Câu hỏi & Đáp án</strong>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="form-group <%= check_errors @survey, :name %>">
      <label class="col-md-4 control-label"
        for="survey_name">Tên bài kiểm tra <small class="text-danger">*</small></label>
      <div class="col-md-5">
        <%= f.text_field :name, class: "form-control ui-wizard-content",
          placeholder: "Nhập tên bài kiểm tra .." %>
        <span class="help-block"><%= show_errors @survey, :name, "name" %></span>
      </div>
    </div>
    <div class="form-group <%= check_errors @survey, :time %>">
      <label class="col-md-4 control-label "
        for="survey_time">Thời gian thực hiện <small>(Phút)</small> <small class="text-danger">*</small></label>
      <div class="col-md-5">
        <%= f.text_field :time, class: "form-control ui-wizard-content",
          placeholder: "Nhập thời gian làm kiểm tra .." %>
        <span class="help-block"><%= show_errors @survey, :time, "time" %></span>
      </div>
    </div>
    <div class="form-group <%= check_errors @survey, :description %>">
      <label class="col-md-4 control-label "
        for="survey_description">Mô tả</label>
      <div class="col-md-5">
        <%= f.text_area :description, class: "form-control ui-wizard-content",
          placeholder: "Nhập mô tả cho bài kiểm tra .." %>
        <span class="help-block"><%= show_errors @survey, :description, "description" %></span>
      </div>
    </div>
  </div>
  <div id="clickable-second" class="step ui-formwizard-content">
    <div class="form-group">
      <div class="col-xs-12">
        <ul class="nav nav-pills nav-justified clickable-steps">
          <li>
            <a href="javascript:void(0)" data-gotostep="clickable-first">
              <strong>1. Thông tin cần thiết</strong>
            </a>
          </li>
          <li class="active">
            <a href="javascript:void(0)" data-gotostep="clickable-second">
              <strong>2. Câu hỏi & Đáp án</strong>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="form-group <%= check_errors @survey, :subject_id %>">
      <label class="col-md-4 control-label"
        for="survey_time">Chọn môn học <small class="text-danger">*</small></label>
      <div class="col-md-5">
        <%= select "survey", "subject_id", @subjects.map{|subject| [subject.name, subject.id]}, {},
            class: "select-chosen" %>
        <span class="help-block"><%= show_errors @survey, :subject_id, "subject_id" %></span>
      </div>
      <div class="col-md-3">
        <label class="switch switch-primary" data-toggle="tooltip"
          data-original-title="Tạo bài kiểm tra cho môn học">
          <%= f.check_box :type_test, {}, "subject_test", "lesson_test" %>
          <span></span>
        </label>
      </div>
    </div>
    <div class="form-group selections-task <%= check_errors @survey, :lesson_id %>">
      <label class="col-md-4 control-label"
        for="survey_time">Chọn bài học của môn <small class="text-danger">*</small></label>
      <div class="col-md-5">
        <%= select "survey", "lesson_id",@lessons.map{|lesson| [lesson.name, lesson.id]}, {},
          class: "select-chosen" %>
        <span class="help-block"><%= show_errors @survey, :lesson_id, "lesson_id" %></span>
      </div>
    </div>
    <div class="form-group" id="questions">
      <%= f.fields_for :questions do |question| %>
      <%= render 'question_fields', f: question %>
      <% end %>
      <div class="col-md-4 control-label question_fields">
        <%= link_to_add_association 'Thêm câu hỏi', f, :questions,class: "btn btn-default" %>
      </div>
    </div>
  </div>
  <div class="form-group form-actions">
    <div class="col-md-8 col-md-offset-4">
      <input type="reset" class="btn btn-sm btn-warning ui-wizard-content ui-formwizard-button" id="back" value="Back">
      <input type="submit" class="btn btn-sm btn-primary ui-wizard-content ui-formwizard-button" id="next" value="Submit">
    </div>
  </div>
<% end %>

app/views/admin/surveys/_question.html.erb
<li>
  <p class="question"><%= question.text %> </p>
  <ul class="answers">
    <%= render partial: "answer", collection: question.answers, as: :answer %>
  </ul>
</li>

app/views/admin/surveys/_question_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <label class="col-md-4 control-label" for="survey_name">Câu hỏi</label>
    <div class="col-md-5">
      <%= f.text_field :text, class: "form-control ui-wizard-content", placeholder: "Nhập câu hỏi .." %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 control-label">
    </div>
    <div class="col-md-8">
      <%= f.fields_for :answers do |answer| %>
      <%= render 'answer_fields', f: answer %>
      <% end %>
      <div class=" question_fields">
        <%= link_to_add_association 'Thêm đáp án', f, :answers,class: "btn btn-default" %>
        <%= link_to_remove_association "Xóa câu hỏi", f, class: "btn btn-default btn-remove-df" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 control-label">
    </div>
    <div class="col-md-5"><hr></div>
  </div>
</div>

app/views/admin/surveys/_survey.html.erb
<% define_color_status_survey survey %>
<tr id="survey_<%= survey.id %>" class="<%= @color %>">
  <td class="text-center"><%= survey.id %></td>
  <td><%= link_to survey.name, admin_survey_path(survey), data: {toggle: "tooltip"},
    title: survey.description %></td>
  <td><%= link_to survey.subject.name, admin_survey_path(survey.subject) %></td>
  <td><%= survey.lesson.name if survey.lesson.present? %></td>
  <td><%= survey.time %></td>
  <td><%= survey.questions.count %></td>
  <td class="status_banner">
    <span class="label label-<%= @class %>"><%= t "surveys.status.#{survey.status}" %></span>
  </td>
  <td class="text-center">
    <div class="btn-group">
      <%= link_to edit_admin_survey_path(survey), class: "btn btn-xs btn-default",
        data: {toggle: "tooltip"}, title: "Chỉnh sửa" do %>
        <i class="fa fa-pencil"></i>
      <% end %>
      <% if survey.course_user_surveys.length == 0 %>
        <%= link_to admin_survey_path(survey), method: :delete, class: "btn btn-xs btn-danger",
          data: {toggle: "tooltip", confirm: "Bạn chắc chắn muốn xóa ?"},
          title: "Xóa", remote: true do %>
          <i class="fa fa-times"></i>
        <% end %>
      <% else %>
        <%= link_to admin_change_status_survey_path(survey), method: :patch, class: "btn btn-xs btn-#{@class}",
          data: {toggle: "tooltip", confirm: "Bạn chắc chắn muốn khóa / mở khóa bài thi này?"},
          title: @title, remote: true do %>
          <i class="fa fa-<%= @icon %>"></i>
        <% end %>
      <% end %>
    </div>
  </td>
</tr>

app/views/admin/surveys/change_status.js.erb
<% if @mes_success %>
  <% define_color_status_survey @survey %>
  $('#survey_<%= @survey.id %> .status_banner').html('<span class="label label-<%= @class %>"><%= t "surveys.status.#{@survey.status}" %></span>');
  $('#survey_<%= @survey.id %> .btn-group').html('<%= link_to edit_admin_survey_path(@survey), class: "btn btn-xs btn-default", data: {toggle: "tooltip"}, title: "Chỉnh sửa" do %><i class="fa fa-pencil"></i><% end %><%= link_to admin_change_status_survey_path(@survey), method: :patch, class: "btn btn-xs btn-#{@class}", data: {confirm: "Bạn chắc chắn muốn khóa / mở khóa bài kiểm tra này?"}, title: @title, remote: true do %><i class="fa fa-<%= @icon %>"></i><% end %>');
  <% if @survey.block? %>
    $('#survey_<%= @survey.id %>').addClass('danger');
    alertify.error('<%= @mes_success %>');
  <% else %>
    $('#survey_<%= @survey.id %>').removeClass('danger');
    alertify.success('<%= @mes_success %>');
  <% end %>
<% elsif @mes_danger %>
  alertify.error('<%= @mes_danger %>');
<% end %>

app/views/admin/surveys/destroy.js.erb
<% if @mes_success.present? %>
  $('#survey_<%= @survey.id %>').remove();
  alertify.success('<%= @mes_success %>');
<% else %>
  alertify.error('<%= @mes_danger %>');
<% end %>

app/views/admin/surveys/edit.html.erb
<% provide :url_path, admin_survey_path %>
<% provide :title, @survey.name %>
<div class="content-header">
  <div class="header-section">
    <h1>
      <i class="gi gi-notes_2"></i><%= @survey.name.capitalize %>
      <br>
      <small>Chỉnh sửa bài kiểm tra</small>
    </h1>
  </div>
</div>
<ul class="breadcrumb breadcrumb-top">
  <li>Bài kiểm tra</li>
  <li><%= link_to @survey.name.capitalize, admin_survey_path(@survey) %></li>
  <li>
    <a href="">Chỉnh sửa</a>
  </li>
</ul>
<!-- END Forms General Header -->
<div class="block">
  <%= render "form" %>
</div>
<script>$(function(){ FormsWizard.init(); });</script>

app/views/admin/surveys/index.html.erb
<% provide :title, "Khóa thực tập" %>
<div class="content-header">
  <div class="header-section">
    <h1>
      <i class="fa fa-table"></i>Danh sách đề thi
    </h1>
  </div>
</div>
<ul class="breadcrumb breadcrumb-top">
  <li>Đề thi</li>
  <li><a href="">Danh sách</a></li>
</ul>
<div class="block full">
  <div class="block-title" id="btn-filter-container">
    <h2><strong>Danh sách</strong></h2>
    <div class="btn-group btn-group-sm pull-right">
      <%= link_to "Sẵn sàng", admin_surveys_path,
        class: "btn btn-primary btn-filter active", remote: true %>
      <%= link_to "Đã khóa", admin_surveys_path(type: "block"),
        class: "btn btn-primary btn-filter", remote: true %>
    </div>
  </div>
  <div class="table-responsive" id="table-content">
    <table id="example-datatable" class="table table-vcenter table-condensed table-bordered">
      <thead>
        <tr>
          <th class="text-center">ID</th>
          <th>Tên</th>
          <th>Môn học</th>
          <th>Bài học</th>
          <th>Thời gian</th>
          <th>Số câu hỏi</th>
          <th>Trạng thái</th>
          <th class="text-center">##</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "survey", collection: @surveys, as: :survey %>
      </tbody>
    </table>
  </div>
  <div class="table-responsive">
    <div style="float: left;">
      Download CSV:
      <%= link_to "Tất cả", admin_course_export_path(format: "csv", type: "all") %> |
      <%= link_to "Đã khóa", admin_course_export_path(format: "xls", type: "block") %>
    </div>
  </div>
</div>
<script>
  $(function(){ TablesSurveys.init(); });
  $(function(){ btnFilterClick.init(); });
</script>

app/views/admin/surveys/index.js.erb
$('#table-content').html("<table id='example-datatable' class='table table-vcenter table-condensed table-bordered'><thead><tr><th class='text-center'>ID</th><th>Tên</th><th>Môn học</th><th>Bài học</th><th>Thời gian</th><th>Số câu hỏi</th><th>Trạng thái</th><th class='text-center'>##</th></tr></thead><tbody><%= j render partial: 'survey', collection: @surveys, as: :survey %></tbody></table>");
$(function(){ TablesSurveys.init(); });

app/views/admin/surveys/new.html.erb
<% provide :url_path, admin_surveys_path %>
<% provide :title, "Tạo bài kiểm tra" %>
<div class="content-header">
  <div class="header-section">
    <h1>
      <i class="gi gi-notes_2"></i>Khởi tạo bài kiểm tra
    </h1>
  </div>
</div>
<ul class="breadcrumb breadcrumb-top">
  <li>Bài kiểm tra</li>
  <li>
    <a href="">Tạo mới</a>
  </li>
</ul>
<div class="block">
  <%= render "form" %>
</div>
<script>$(function(){ FormsWizard.init(); });</script>

app/views/admin/surveys/reload_lesson.js.erb
<% if @mes_error.present? %>
  alertify.error("<%= @mes_error %>");
  location.reload();
<% else %>
  $('.selections-task').html('<label class="col-md-4 control-label" for="survey_time">Chọn bài học của môn</label><div class="col-md-5"><%= j select "survey", "lesson_id", @lessons.map{|lesson| [lesson.name, lesson.id]}, {}, class: "form-control" %></div>');
<% end %>
$('.spinner').delay(1000).hide(0);

app/views/admin/surveys/show.html.erb
<% provide :title, @survey.name %>
<div class="content-header">
  <div class="header-section">
    <h1>
      <i class="fa fa-globe"></i><%= @survey.name.upcase %><br>
      <small><%= @survey.description %></small>
    </h1>
  </div>
</div>
<ul class="breadcrumb breadcrumb-top">
  <li>Bài kiểm tra</li>
  <li><a href=""><%= @survey.name.capitalize %></a></li>
</ul>
<div class="row">
  <ol class="questions">
    <%= render partial: "question", collection: @questions, as: :question %>
  <ol>
</div>