config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root "main#index"
  end
  root "introduce#index"
  devise_for :users, skip: %i(sessions registrations), controllers: {passwords: "devises/passwords"}
  as :user do
    get "/login", to: "devises/sessions#new", as: :new_user_session
    post "/login", to: "devises/sessions#create", as: :user_session
    delete "/logout", to: "devises/sessions#destroy", as: :destroy_user_session
    get "/users/edit", to: "devise/registrations#edit", as: :edit_user_registration
    put "/users", to: "devise/registrations#update", as: :user_registration
    get "profiles/:id", to: "users#show", as: :profiles
    patch  "user/avatar/:id", to: "users#change_avatar", as: :change_avatar
  end
  namespace :admin do
    as :user do
      patch "user/status/:id", to: "users#change_status_user", as: :change_status_user
      get "users/export/:type", to: "users#export", as: :user_export
      post "users/import", to: "users#import", as: :user_import
    end
    resources :users, except: %i(show destroy)
    resources :courses
    patch "course/status/:id", to: "courses#change_status", as: :change_status_course
    get "courses/export/:type", to: "courses#export", as: :course_export
    get "courses/export/course/:id", to: "courses#export_course", as: :course_export_course
    post "courses/import", to: "courses#import", as: :course_import
    resources :subjects
    patch "subject/status/:id", to: "subjects#change_status", as: :change_status_subject
    get "subjects/export/file", to: "subjects#export", as: :subject_export
    get "subjects/export/subject/:id", to: "subjects#export_subject", as: :subject_export_subject
    post "subjects/import", to: "subjects#import", as: :subject_import
    post "subjects/import/lessons", to: "subjects#import_lesson", as: :subject_import_lesson
    post "subjects/import/links", to: "subjects#import_link", as: :subject_import_link
    resources :lessons
    get "course/:course_id/subject/:subject_id", to: "course_subjects#show", as: :show_subject_course
    get "course/:course_id/subject/:subject_id/:status", to: "course_subjects#update", as: :update_status_cs
    resources :course_users
    resources :lessons, except: %i(new create destroy)
    get "lessons/export/exam/:id", to: "lessons#export_lesson_exam", as: :export_lesson_exam
    resources :companies, only: %i(show edit update)
  end

  namespace :trainer do
    resources :users, only: :index
    resources :courses, only: :index
  end

  namespace :trainee do
    get "exam_lessons/new/:course_user_lesson_id", to: "exam_lessons#new", as: :new_exam_lesson
    resources :exam_lessons, except: %i(new index)
    get "exam_lessons/course_user_lesson/:course_user_lesson_id", to: "exam_lessons#show_test_of_lesson", as: :show_test_of_lesson
  end
  get "myexams", to: "trainee/exams#index"
  get "course/:id", to: "admin/courses#show", as: :course
  get "course/:course_id/subject/:subject_id", to: "admin/course_subjects#show", as: :trainer_course_subject

  get "mycourses", to: "trainee/courses#index", as: :mycourses
  get "mycourse/:id", to: "admin/courses#show", as: :mycourse
  get "mycourse/:course_id/subject/:subject_id", to: "admin/course_subjects#show", as: :course_subject
  get "report/progress/:id/:status", to: "trainee/course_user_lessons#update", as: :report_progress

  get "/about", to: "test_templatee2#about", as: "about"
  get "/form/course", to: "test_templatee2#form_course", as: "form_course"
  get "/form/course/edit", to: "test_templatee2#form_course_edit", as: "form_course_edit"

  resources :registrations
  post "/registrations/accept", to: "registrations#accept_action", as: :accept_action
end

app/views/component/profile_component/_avatar_box_profile.html.erb
<div class="user-panel-left">
  <div class="box box-custom-top">
    <div class="box-body box-profile">
      <div class="avatar-container clearfix">
        <%= show_avatar_for @user %>
        <% if can? :update, @user %>
          <div class="upload-btn-overlay clearfix">
            <div class="row">
              <div class="col-md-12">
                <%= form_for @user, url: change_avatar_path(@user.id), method: :patch,
                  html: {class: "avt_form"}, remote: true do |f| %>
                  <%= f.file_field :avatar, id: "avatarUser", class: "form-control" %>
                  <%= f.submit "Save", class: "btn btn-primary load-spinner" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <h3 class="profile-username text-center"><%= @user.name %></h3>
      <p class="text-muted text-center">
        <b>Email </b><br><%= @user.email %><br>
        <b>Phone </b><br><%= @user.phone %><br>
      </p>
    </div>
  </div>
</div>

app/views/component/profile_component/_course.html.erb
<tr>
  <td>
    <%= link_to course.name, link_course_profile(course) %>
  </td>
  <td class="text-center" style="width: 72px;">
    <%= image_tag course.avatar.url, class: "img-member img-circle img-responsive" %>
  </td>
</tr>

app/views/component/profile_component/_main_box_profile.html.erb
<div class="nav-tabs-custom">
  <div class="nav nav-tabs nav-user">
    <li class="active"><a href="#profile" data-toggle="tab">Hồ sơ</a></li>
  </div>
  <div class="tab-content">
    <div class=" profile-container clearfix active">
      <div class="col-md-12">
        <div class="box" id="main-profile-1">
          <% if can? :update, @user %>
            <%= link_to edit_admin_user_path(@user), class: "btn btn-xs btn-default cog-profile", remote: true do %>
              <i class="fa fa-cog"></i>
            <% end %>
          <% end %>
          <table class="table table-user-information">
            <tbody>
              <tr>
                <td>Họ tên</td>
                <td><%= @user.name %></td>
              </tr>
              <tr>
                <td>Email</td>
                <td><%= @user.email %></td>
              </tr>
              <tr>
                <td>Giới tính</td>
                <td><%= @user.gender %></td>
              </tr>
              <tr>
                <td>Ngày sinh</td>
                <td><%= @user.birthday %></td>
              </tr>
              <tr>
                <td>Đại học</td>
                <td><%= @user.university %></td>
              </tr>
              <tr>
                <td>Chương trình</td>
                <td><%= @user.program %></td>
              </tr>
              <tr>
                <td>Bắt đầu thực tập</td>
                <td><%= @user.created_at %></td>
              </tr>
              <tr></tr>
              <tr>
                <td>Mô tả</td>
                <td>
                  <p></p>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/component/profile_component/_references_box_profile.html.erb
<% define_course_profile @user %>
<div class="block">
  <div class="block-title">
    <div class="block-options pull-right">
      <em>số lượng: <%= @course_joins.length %></em>
    </div>
    <h2>
      <strong>Khóa thực tập</strong> tham gia
    </h2>
  </div>
  <table class="table table-striped table-vcenter table-trainer">
    <tbody>
      <%= render partial: "component/profile_component/course",
        collection: @course_joins, as: :course %>
    </tbody>
  </table>
</div>
<% if @user.trainer? %>
  <div class="block">
    <div class="block-title">
      <div class="block-options pull-right">
        <em>số lượng: <%= @course_owners.length %></em>
      </div>
      <h2>
        <strong>Khóa thực tập</strong> chủ nhiệm
      </h2>
    </div>
    <table class="table table-striped table-vcenter table-trainer">
      <tbody>
        <%= render partial: "component/profile_component/course",
          collection: @course_owners, as: :course %>
      </tbody>
    </table>
  </div>
<% end %>