config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root "main#index"
  end
  root "introduce#index"
  devise_for :users, skip: %i(sessions registrations), controllers: {passwords: "devises/passwords"}
  as :user do
    get "/login", to: "devises/sessions#new", as: :new_user_session
    post "/login", to: "devises/sessions#create", as: :user_session
    delete "/logout", to: "devises/sessions#destroy", as: :destroy_user_session
    get "/users/edit", to: "devise/registrations#edit", as: :edit_user_registration
    put "/users", to: "devise/registrations#update", as: :user_registration
    get "profiles/:id", to: "users#show", as: :profiles
    patch  "user/avatar/:id", to: "users#change_avatar", as: :change_avatar
  end
  namespace :admin do
    as :user do
      patch "user/status/:id", to: "users#change_status_user", as: :change_status_user
      get "users/export/:type", to: "users#export", as: :user_export
      post "users/import", to: "users#import", as: :user_import
    end
    resources :users, except: %i(show destroy)
    resources :courses
    patch "course/status/:id", to: "courses#change_status", as: :change_status_course
    get "courses/export/:type", to: "courses#export", as: :course_export
    get "courses/export/course/:id", to: "courses#export_course", as: :course_export_course
    post "courses/import", to: "courses#import", as: :course_import
    resources :subjects
    patch "subject/status/:id", to: "subjects#change_status", as: :change_status_subject
    get "subjects/export/file", to: "subjects#export", as: :subject_export
    get "subjects/export/subject/:id", to: "subjects#export_subject", as: :subject_export_subject
    post "subjects/import", to: "subjects#import", as: :subject_import
    post "subjects/import/lessons", to: "subjects#import_lesson", as: :subject_import_lesson
    post "subjects/import/links", to: "subjects#import_link", as: :subject_import_link
    resources :lessons
    get "course/:course_id/subject/:subject_id", to: "course_subjects#show", as: :show_subject_course
    get "course/:course_id/subject/:subject_id/:status", to: "course_subjects#update", as: :update_status_cs
    resources :course_users
    resources :lessons, except: %i(new create destroy)
    get "lessons/export/exam/:id", to: "lessons#export_lesson_exam", as: :export_lesson_exam
    resources :companies, only: %i(show edit update)
  end

  namespace :trainer do
    resources :users, only: :index
    resources :courses, only: :index
  end

  namespace :trainee do
    get "exam_lessons/new/:course_user_lesson_id", to: "exam_lessons#new", as: :new_exam_lesson
    resources :exam_lessons, except: %i(new index)
    get "exam_lessons/course_user_lesson/:course_user_lesson_id", to: "exam_lessons#show_test_of_lesson", as: :show_test_of_lesson
  end
  get "myexams", to: "trainee/exams#index"
  get "course/:id", to: "admin/courses#show", as: :course
  get "course/:course_id/subject/:subject_id", to: "admin/course_subjects#show", as: :trainer_course_subject

  get "mycourses", to: "trainee/courses#index", as: :mycourses
  get "mycourse/:id", to: "admin/courses#show", as: :mycourse
  get "mycourse/:course_id/subject/:subject_id", to: "admin/course_subjects#show", as: :course_subject
  get "report/progress/:id/:status", to: "trainee/course_user_lessons#update", as: :report_progress

  get "/about", to: "test_templatee2#about", as: "about"
  get "/form/course", to: "test_templatee2#form_course", as: "form_course"
  get "/form/course/edit", to: "test_templatee2#form_course_edit", as: "form_course_edit"

  resources :registrations
  post "/registrations/accept", to: "registrations#accept_action", as: :accept_action
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, length: {maximum: 250}, presence: true
  validates :description, length: {maximum: 5000}, presence: true
  validates :address, length: {maximum: 250}, presence: true
  validates :city, length: {maximum: 250}, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 250}, format: {with: VALID_EMAIL_REGEX}
  validates :phone, length: {maximum: 12},format: { with: /0+\d{8,12}/, message: "Số điện thoại định dạng không hợp lệ" }, presence: true


  mount_uploader :image_1, CompanyImage1Uploader
  mount_uploader :image_2, CompanyImage2Uploader
  mount_uploader :image_3, CompanyImage3Uploader
  mount_uploader :image_4, CompanyImage4Uploader
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < ApplicationController
  load_and_authorize_resource

  def show
  end

  def edit
  end

  def update
    if @company.update_attributes params_company
      @mes_success = "Cập nhật thông tin công ty thành công"
    else
      @mes_danger = "Cập nhật thông tin công ty thất bại"
    end
  end

  private

  def params_company
    params.require(:company).permit :name, :email, :phone, :address, :city, :description,
      :image_1, :image_2, :image_3, :image_4
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/views/admin/companies/_content.html.erb
<div class="nav-tabs-custom">
  <div class="nav nav-tabs nav-user">
    <li class="active"><a href="#profile" data-toggle="tab">Hồ sơ công ty</a></li>
  </div>
  <div class="tab-content">
    <div class=" profile-container clearfix active">
      <div class="col-md-12">
        <div class="box" id="main-profile-1">
          <%= link_to edit_admin_company_path(@company), class: "btn btn-xs btn-default cog-profile", remote: true do %>
            <i class="fa fa-cog"></i>
          <% end %>
          <table class="table table-user-information">
            <tbody>
              <tr>
                <td class="td-title">Tên công ty</td>
                <td><%= @company.name %></td>
              </tr>
              <tr>
                <td class="td-title">Email</td>
                <td><%= @company.email %></td>
              </tr>
              <tr>
                <td class="td-title">Số điện thoại</td>
                <td><%= @company.phone %></td>
              </tr>
              <tr>
                <td class="td-title">Địa chỉ</td>
                <td><%= @company.address %></td>
              </tr>
              <tr>
                <td class="td-title">Thành phố</td>
                <td><%= @company.city %></td>
              </tr>
              <tr>
                <td class="td-title">Mô tả</td>
                <td><%= @company.description %></td>
              </tr>
              <tr>
                <td class="td-title">Ảnh 1</td>
                <td><%= image_tag @company.image_1.url, class: "img-responsive", alt: "image 1" %></td>
              </tr>
              <tr>
                <td class="td-title">Ảnh 2</td>
                <td><%= image_tag @company.image_2.url, class: "img-responsive", alt: "image 2" %></td>
              </tr>
              <tr>
                <td class="td-title">Ảnh 3</td>
                <td><%= image_tag @company.image_3.url, class: "img-responsive", alt: "image 3" %></td>
              </tr>
              <tr>
                <td class="td-title">Ảnh 4</td>
                <td><%= image_tag @company.image_4.url, class: "img-responsive", alt: "image 4" %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/companies/_edit.html.erb
<%= form_for @company, method: :patch, url: admin_company_path,
  html: {class: "form-horizontal form-bordered", id: "edit_user_form"}, remote: true do |f| %>
  <div class="form-group <%= check_errors @company, :name %>">
    <label class="col-md-3 control-label" for="company_name">Tên công ty <span class="text-danger">*</span></label>
    <div class="col-md-9">
      <%= f.text_field :name, class: "form-control", placeholder: "Nhập tên công ty ..", required: true %>
      <span class="text-danger" id="name-error"><%= show_errors @company, :name, "name" %></span>
    </div>
  </div>
  <div class="form-group <%= check_errors @company, :email %>">
    <label class="col-md-3 control-label" for="company_email">Email <span class="text-danger">*</span></label>
    <div class="col-md-9">
      <%= f.email_field :email, class: "form-control", placeholder: "Nhập email công ty ..", required: true %>
      <span class="text-danger" id="email-error"><%= show_errors @company, :email, "email" %></span>
    </div>
  </div>
  <div class="form-group <%= check_errors @company, :phone %>">
    <label class="col-md-3 control-label" for="company_phone">Số điện thoại </label>
    <div class="col-md-9">
      <%= f.text_field :phone, class: "form-control", placeholder: "Nhập số điện thoại công ty..", required: true %>
      <span class=" text-danger" id="phone-error"><%= show_errors @company, :phone, "phone" %></span>
    </div>
  </div>
  <div class="form-group <%= check_errors @company, :address %>">
    <label class="col-md-3 control-label" for="company_address">Địa chỉ công ty </label>
    <div class="col-md-9">
      <%= f.text_field :address, class: "form-control", placeholder: "Nhập địa chỉ công ty ..", required: true %>
      <span class="text-danger" id="address-error"><%= show_errors @company, :address, "address" %></span>
    </div>
  </div>
  <div class="form-group <%= check_errors @company, :city %>">
    <label class="col-md-3 control-label" for="company_city">Thành phố </label>
    <div class="col-md-9">
      <%= f.text_field :city, class: "form-control", placeholder: "Nhập thành phố ..", required: true %>
      <span class="text-danger" id="city-error"><%= show_errors @company, :city, "city" %></span>
    </div>
  </div>
  <div class="form-group <%= check_errors @company, :description %>">
    <label class="col-md-3 control-label" for="company_description">Mô tả </label>
    <div class="col-md-9">
      <%= f.text_area :description, class: "form-control", placeholder: "Nhập mô tả công ty ..", required: true, row: 6 %>
      <span class="text-danger" id="description-error"><%= show_errors @company, :description, "description" %></span>
    </div>
  </div>
  <div class="form-group <%= check_errors @company, :image_1 %>">
    <label class="col-md-4 control-label" for="company_image_1">Hình 1 </label>
    <div class="col-md-5">
      <%= f.file_field :image_1, id: "image_1" %>
      <%= image_tag(@company.image_1.url, class: "img-responsive", id: "com_img1") %>
      <span class="text-danger"><%= show_errors @company, :image_1, "image_1" %></span>
      <span class="help-block">Đề xuất sử dụng ảnh kích thước 1000x150 để có trải nghiệm tốt nhất</span>
    </div>
  </div>
  <div class="form-group <%= check_errors @company, :image_2 %>">
    <label class="col-md-4 control-label" for="company_image_2">Hình 2 </label>
    <div class="col-md-5">
      <%= f.file_field :image_2, id: "image_2" %>
      <%= image_tag(@company.image_2.url, class: "img-responsive", id: "com_img2") %>
      <span class="text-danger"><%= show_errors @company, :image_2, "image_2" %></span>
      <span class="help-block">Đề xuất sử dụng ảnh kích thước 1000x150 để có trải nghiệm tốt nhất</span>
    </div>
  </div>
  <div class="form-group <%= check_errors @company, :image_3 %>">
    <label class="col-md-4 control-label" for="company_image_3">Hình 3 </label>
    <div class="col-md-5">
      <%= f.file_field :image_3, id: "image_3" %>
      <%= image_tag(@company.image_3.url, class: "img-responsive", id: "com_img3") %>
      <span class="text-danger"><%= show_errors @company, :image_3, "image_3" %></span>
      <span class="help-block">Đề xuất sử dụng ảnh kích thước 1000x150 để có trải nghiệm tốt nhất</span>
    </div>
  </div>
  <div class="form-group <%= check_errors @company, :image_4 %>">
    <label class="col-md-4 control-label" for="company_image_4">Hình 4 </label>
    <div class="col-md-5">
      <%= f.file_field :image_4, id: "image_4" %>
      <%= image_tag(@company.image_4.url, class: "img-responsive", id: "com_img4") %>
      <span class="text-danger"><%= show_errors @company, :image_4, "image_4" %></span>
      <span class="help-block">Đề xuất sử dụng ảnh kích thước 1000x150 để có trải nghiệm tốt nhất</span>
    </div>
  </div>
  <div class="form-group form-actions">
    <div class="col-md-9 col-md-oét-3">
      <%= f.submit "Lưu thông tin", class: "btn btn-sm btn-primary" %>
      <button type="button" class="btn btn-sm btn-danger" id="edit_profile_cancle">Hủy</button>
    </div>
  </div>
<% end %>

app/views/admin/companies/edit.js.erb
$('#main-profile-1').hide(500);
$('#main-profile-1').after('<%= j render "edit" %>');

app/views/admin/companies/show.html.erb
<% provide :title, "Thông tin công ty" %>
<div class="content-header">
  <div class="header-section">
    <h1>
      <i class="gi gi-notes"></i>THÔNG TIN CÔNG TY
    </h1>
  </div>
</div>
<ul class="breadcrumb breadcrumb-top">
  <li>Home</li>
  <li><a href="">Thông tin công ty</a></li>
</ul>
<div class="row">
  <div class="col-md-12 user-profile-content">
    <div class="col-md-9 " id="profile-content">
      <%= render "admin/companies/content" %>
    </div>
  </div>
</div>
<style type="text/css">
  .td-title{
    min-width: 100px;
    font-weight: 600;
  }
</style>

app/views/admin/companies/update.js.erb
<% if @mes_danger.present? %>
  alertify.error('<%= @mes_danger %>');
  $('#name-error').text('<%= @company.errors[:name][0] %>');
  $('#phone-error').text('<%= @company.errors[:phone][0] %>');
  $('#address-error').text('<%= @company.errors[:address][0] %>');
  $('#city-error').text('<%= @company.errors[:city][0] %>');
  $('#description-error').text('<%= @company.errors[:description][0] %>');
  $('#email-error').text('<%= @company.errors[:email][0] %>');
<% else %>
  $('#profile-content').html('<%= j render "admin/companies/content" %>');
  alertify.success('<%= @mes_success %>');
<% end %>